swagger: '2.0'
info:
  title: NodeJs API
  description: Api com rotas de usuário, post e profiles
  version: 1.0.0
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /:
    get:
      description: ''
      responses:
        '200':
          description: OK
  /posts/:
    get:
      description: ''
      responses:
        default:
          description: ''
    post:
      description: ''
      responses:
        default:
          description: ''
  /posts/author/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
  /posts/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
  /users/:
    get:
      description: ''
      responses:
        default:
          description: ''
    post:
      description: ''
      responses:
        default:
          description: ''
  /users/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
  /profiles/:
    get:
      description: ''
      responses:
        default:
          description: ''
    post:
      description: ''
      responses:
        default:
          description: ''
  /profiles/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        default:
          description: ''
